### ISSUE TITLE
"No stack trace found" for Go

### ISSUE THREAD

**Issue by brighama** [mattboehm/vim-unstack#23] opened 2014-11-06 18:35 UTC
Not sure if I'm doing it right, but the following snippet gives me "No stack trace found" when I apply :UnstackFromSelection or :UnstackFromClipboard

goroutine 19 [finalizer wait]:
runtime.park(0x4132d0, 0x65b178, 0x659ce9)
    /usr/local/go/src/pkg/runtime/proc.c:1369 +0x89
runtime.parkunlock(0x65b178, 0x659ce9)
    /usr/local/go/src/pkg/runtime/proc.c:1385 +0x3b
runfinq()
    /usr/local/go/src/pkg/runtime/mgc0.c:2644 +0xcf
runtime.goexit()
    /usr/local/go/src/pkg/runtime/proc.c:1445

**Comment by mattboehm** [comment] 2019-04-18 14:31
Closing this as I've never heard back and was unable to reproduce this locally, but if anyone is still running into this issue, please let me know.

**Closed by mattboehm** 2019-04-18 14:31 UTC
